goldprice/__init__.py
from flask import Flask, render_template


def create_app():
    app = Flask(__name__)

    from .views import main_views
    from .views import predict_views
    app.register_blueprint(main_views.bp)
    app.register_blueprint(predict_views.bp)
    return app


if __name__ == '__main__':
    create_app().run()

goldprice/views/main_views.py
from flask import Blueprint, render_template

bp = Blueprint('main',__name__,url_prefix='/')

@bp.route('/')
def main_view():
    return render_template('main.html')

goldprice/views/predict_views.py
from flask import Blueprint, render_template, request
import numpy as np
import pickle

bp = Blueprint('predict',__name__,url_prefix='/predict')

loaded_model = pickle.load(open("model1.pkl", "rb"))
# with open('model/model1.pkl', 'rb') as file:
#     model = pickle.load(file)

@bp.route('/')
def inputdata():
    return render_template('predict.html')

@bp.route('/result',methods=['POST'])
def printresult():

    kospi = float(request.form['kospi'])
    kosdaq = float(request.form['kosdaq'])
    sp500 = float(request.form['sp500'])
    nasdaq = float(request.form['nasdaq'])
    exchange = float(request.form['exchangerate'])
    bok = float(request.form['bok'])
    btc = float(request.form['btc'])

    data = np.array([kospi,kosdaq,sp500,nasdaq,exchange,bok,btc]).reshape([1,-1])

    pred = loaded_model.predict(data)
    result = int(pred)
   
    return render_template('result.html',data=result)

goldprice/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gold is mine</title>
</head>
<body>
    <h1>Gold is mine!</h1>
    <p>
        <a href="/predict">알아보자!</a>
        <iframe width="600" height="450" src="https://datastudio.google.com/embed/reporting/c108feec-4678-4a41-bf64-2ea91cacb5f1/page/cpKwC" frameborder="0" style="border:0" allowfullscreen></iframe>
    </p>
</body>
</html>

goldprice/templates/predict.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Predict!</title>
</head>
<body>
    <h1>How much?</h1>
    <form action="{{url_for('predict.printresult')}}" method="POST">
        <p>KOSPI</p>
        <input type="range" name="kospi" value="2700" min="1500" max="4000" step="1" oninput="this.nextElementSibling.value = this.value"> <output>2700</output><br>
        <p>KOSDAQ</p>
        <input type="range" name="kosdaq" value="800" min="300" max="2000" step="1" oninput="this.nextElementSibling.value = this.value"> <output>800</output><br>
        <p>S&P500</p>
        <input type="range" name="sp500" value="2700" min="2000" max="10000" step="10" oninput="this.nextElementSibling.value = this.value"> <output>2700</output><br>
        <p>NASDAQ</p>
        <input type="range" name="nasdaq" value="12000" min="5000" max="20000" step="10" oninput="this.nextElementSibling.value = this.value"> <output>12000</output><br>
        <p>원/달러 환율</p>
        <input type="range" name="exchangerate" value="1200" min="1000" max="2000" step="1" oninput="this.nextElementSibling.value = this.value"> <output>1200</output><br>
        <p>한국은행 기준금리</p>
        <input type="range" name="bok" value="1.5" min="0.5" max="2.0" step="0.05" oninput="this.nextElementSibling.value = this.value"> <output>1.5</output><br>
        <!-- <input type="range" name="btc" value="2700" min="1500" max="3000" step="0.5" oninput="this.nextElementSibling.value = this.value"> <output>2700</output><br> -->
        <!-- <p>코스피</p><input type='text' placeholder="KOSPI" required name="kospi"> -->
        <!-- <p>코스닥</p><input placeholder="KODAQ" required name="kosdaq">
        <p>S&P500</p><input placeholder="S&P500" required name="sp500">
        <p>NASDAQ</p><input placeholder="NASDAQ" required name="nasdaq">
        <p>원/달러 환율</p><input placeholder="환율" required name="exchangerate">
        <p>한국은행기준금리</p><input placeholder="KOSPI" required name="bok"> -->
        <p>비트코인</p><input placeholder="BTC" required name="btc">
        <br>
        <br>
        <input type="submit" value="Submit" name="확인" >
        <!-- <button>submit</button> -->
    </form>
    <br>
</body>
</html>

goldprice/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>result</title>
</head>
<body>
    <p>{{ data }}원은 어떠시렵니까?</p>
    <button>
        <a href="/">
            돌아가기
        </a>
    </button>
</body>
</html>